package.json
src/config-fetcher.ts

I replaced ky with got and using tunnel package to create an agent as proxy.
It should resolve #7

add proxy support with got and node-tunnel

---

tsconfig.json

this generates a `.d.ts` file which allows editors such as Atom or Visual Studio code to use code completion and other features that integrates the SDK into the editor.

Add option to generate declaration map

---

package-lock.json
package.json
src/config-fetcher.ts

September dep updates

---

package-lock.json
package.json
src/config-fetcher.ts

Use latest common & the new fetcher API.

Use latest common & the new fetcher API

---

package-lock.json
package.json
src/config-fetcher.ts

Add debug logs to trace down errors in the SDK.

Adding debug logs to the SDK

---

package-lock.json
package.json
src/client.ts
test/client-tests.ts
test/integration-tests.ts

Export factory function for flag overrides.

Export factory function for flag overrides

---

.npmignore
gulpfile.js
package-lock.json
package.json
src/client.ts
src/config-fetcher.ts
src/version.ts

Passing the real SDK version and type to common-js.

SDK version fix

---

package-lock.json
package.json

:pray: August dependency updates

---

.npmignore

Updates .npmignore

---

samples/console-esm/package-lock.json
samples/console-esm/package.json
samples/console/package-lock.json
samples/console/package.json
samples/customcache/package-lock.json
samples/customcache/package.json
samples/expresswithdocker/package-lock.json
samples/expresswithdocker/package.json
samples/realtimeupdate/package-lock.json
samples/realtimeupdate/package.json
update-samples.sh

Updates samples to use the newly released version

Updates samples to use the newly released version

---

README.md
package-lock.json
package.json

Specifying Node.JS version with engine-strict=true and adding a badge with the supported SDK version.
Provide links to issues relating to this pull request

Nodeversion

---

package-lock.json
package.json

Prepare v9.1.1 release

---

package-lock.json
package.json
src/client.ts
src/config-fetcher.ts
test/client-tests.ts
test/helpers/fakes.ts
test/helpers/utils.ts
test/http-tests.ts
test/integration-tests.ts

Removes deprecated code.
Breaking changes:
* Removes the `createClient`, `createClientWithAutoPoll`, `createClientWithManualPoll`, `createClientWithLazyLoad` factory functions. Alternative: `getClient`.

Adjust SDK to configcat-common v8.0

---

CHANGELOG.md
README.md
package-lock.json
package.json
src/client.ts

Prepare v10.0.0 release

---

package-lock.json
package.json

Prepare v10.0.1 release

---

package-lock.json
package.json
src/client.ts

Prepare v10.1.0 release

---

package-lock.json
package.json

Prepare v10.1.1 release
Fixes:
* Downgrade TypeScript compiler version to v4.0 for better compatibility.

Prepare v10.1.1 release

---

package-lock.json

October 2023 security updates

---

.github/workflows/node-ci.yml
package-lock.json
package.json
samples/console-esm/index.js
samples/console/index.js
samples/customcache/index.js
src/client.ts
test/client-tests.ts
test/integration-tests.ts

Prepare v11.0.0 (Catnip) release

Prepare v11.0.0 (Catnip) release

---

samples/console-esm/package-lock.json
samples/console-esm/package.json
samples/console/package-lock.json
samples/console/package.json
samples/customcache/package-lock.json
samples/customcache/package.json
samples/expresswithdocker/package-lock.json
samples/expresswithdocker/package.json
samples/realtimeupdate/package-lock.json
samples/realtimeupdate/package.json

Update samples to v11.0.0

---

package-lock.json
package.json
test/special-character-tests.ts
tsconfig.json

* Implement integration tests for making sure that Unicode characters outside the ASCII range are handled correctly.
* Minor dev env improvements.
* Update to configcat-common v9.1.0.
https://trello.com/c/4gd0Y3EA

Minor improvements

---

package-lock.json

February 2024 security updates

February 2024 security updates

---

package-lock.json

April 2024 security updates

---

package-lock.json
package.json

Prepare v11.3.1 release

---

.vscode/launch.json
package-lock.json
package.json
src/config-fetcher.ts
test/http-tests.ts

Prepare v11.4.0 release
n/a
n/a
n/a

Prepare v11.4.0 release
